app/dashboards/controllers.py
# Import flask dependencies
from flask import Blueprint, render_template, session, request,\
    redirect, url_for
from saved_data_processing import graph_generator_DB, graph_generator_pp_DB
from realtime_data_processing import graph_generator_pp, graph_generator
from app.init_database import mongo
from app.dashboards import model


# Define the blueprint: 'dashboards', set its url prefix: app.url/dashboards
dashboards = Blueprint('dashboards', __name__, url_prefix='/dashboards')

pickle_saver = True  # Initially True as pickle saving is default
graph_data_stats = []  # Contains graph Data loaded globally for get request
project_lists = []  # Contains project list globally for get request
username = ''  # For saving username globally
password = ''  # For saving password globally
server = ''  # For saving server url globally
ssl = ''  # For saving username globally
role_exist = ''
db = False  # For specifying that connected to DB or pickle


# Set the route and accepted methods
@dashboards.route('/stats/', methods=['POST', 'GET'])
def stats():

    if request.method == "POST":

        global username, server, password, ssl
        user_details = request.form
        username = user_details['username']
        password = user_details['password']
        server = user_details['server']
        ssl = False if user_details.get('ssl') is None else True
        global graph_data_stats
        global project_lists
        global db
        plotting_object = graph_generator.GraphGenerator(username,
                                                         password,
                                                         server,
                                                         ssl)
        graph_data_stats = plotting_object.graph_generator()
        project_lists = plotting_object.project_list_generator()

        # Disconnecting the api session
        del plotting_object

        if graph_data_stats == [] or type(graph_data_stats) == int:
            session['error'] = graph_data_stats
            return redirect(url_for('auth.login'))
        else:
            project_list = project_lists[0]
            project_list_ow_co_me = project_lists[1]
            graph_data = graph_data_stats[0]
            stats_data = graph_data_stats[1]
            return render_template('dashboards/stats_dashboards.html',
                                   graph_data=graph_data,
                                   project_list=project_list,
                                   stats_data=stats_data,
                                   project_list_ow_co_me=project_list_ow_co_me,
                                   username=username.capitalize(),
                                   server=server,
                                   db=db)
    else:
        # If user reloads page without logging out then should again show data

        if graph_data_stats == [] or type(graph_data_stats) == int:
            session['error'] = graph_data_stats
            return redirect(url_for('auth.login'))
        elif db:
            return redirect(url_for('dashboards.stats_db'))
        else:
            project_list = project_lists[0]
            project_list_ow_co_me = project_lists[1]
            graph_data = graph_data_stats[0]
            stats_data = graph_data_stats[1]
            return render_template('dashboards/stats_dashboards.html',
                                   graph_data=graph_data,
                                   project_list=project_list,
                                   stats_data=stats_data,
                                   project_list_ow_co_me=project_list_ow_co_me,
                                   username=username.capitalize(),
                                   server=server,
                                   db=db)


# this route give the details of the project
@dashboards.route('project/<id>', methods=['GET'])
def project(id):

    global username, password, server, ssl

    data_array = graph_generator_pp.GraphGenerator(
        username, password, server, ssl, id
    ).graph_generator()

    graph_data = data_array[0]
    stats_data = data_array[1]
    members = data_array[2]['member(s)']
    users = data_array[2]['user(s)']
    collaborators = data_array[2]['Collaborator(s)']
    owners = data_array[2]['Owner(s)']
    last_accessed = data_array[2]['last_accessed(s)']
    insert_users = data_array[2]['insert_user(s)']
    insert_date = data_array[2]['insert_date']
    access = data_array[2]['access']
    name = data_array[2]['name']
    last_workflow = data_array[2]['last_workflow']

    return render_template(
        'dashboards/stats_dashboards_pp.html',
        graph_data=graph_data,
        stats_data=stats_data,
        username=username.capitalize(),
        server=server,
        db=db,
        members=members,
        users=users,
        collaborators=collaborators,
        owners=owners,
        last_accessed=last_accessed,
        insert_date=insert_date,
        insert_users=insert_users,
        access=access,
        name=name,
        last_workflow=last_workflow,
        id=id)


# Logout route
@dashboards.route('/logout/', methods=['GET'])
def logout():

    global graph_data_stats, username, password, ssl
    global server, pickle_saver, role_exist
    pickle_saver = True
    graph_data_stats = []
    username = ''
    password = ''
    server = ''
    ssl = ''
    role_exist = ''

    if 'username' in session:
        del session['username']
    session['error'] = -1

    global db
    if db:
        db = False
        return redirect(url_for('auth.login_DB'))
    else:
        return redirect(url_for('auth.login'))


@dashboards.route('/db/stats/', methods=['GET', 'POST'])
def stats_db():
    global db
    db = True

    if request.method == 'POST':
        global username, server
        user_details = request.form
        username = user_details['username']
        password = user_details['password']
        server = user_details['server']
        ssl = False if user_details.get('ssl') is None else True
        save_to_DB = False if request.form.get('DB') is None else True
        global graph_data_stats
        global project_lists

        if not save_to_DB:  # If save_to_DB is false then use pickle
            if 'username' in session and graph_data_stats != []:
                session['error'] = "Already logged in"
            else:
                exist = model.user_exists(username, password, server, ssl)

                global role_exist

                if type(exist) == int:
                    config = model.user_role_config(username)

                    if config:
                        if username in config['user roles']:
                            role_exist = config['user roles'][username]
                        else:
                            role_exist = 'guest'

                        user_data = model.load_users_data_pk(server)
                        resources = model.load_resources_pk(server)
                        resources_bbrc = model.load_resources_bbrc_pk(
                            server)

                        if user_data is not None:
                            plotting_object = graph_generator_DB.\
                                GraphGenerator(
                                    username,
                                    user_data['info'],
                                    role_exist,
                                    config['project_visible'],
                                    resources,
                                    resources_bbrc)

                            graph_data_stats = plotting_object.\
                                graph_generator()

                            project_lists = plotting_object.\
                                project_list_generator()
                        else:
                            session['error'] = 'Wrong server or data'
                            'not downloaded'

                    else:
                        session['error'] = "Wrong Password"
                        role_exist = ''
                else:
                    session['error'] = exist
        else:  # Use Database and pickle saver value to False over dashboard
            global pickle_saver
            pickle_saver = False

            exist = model.user_exists(username, password, server, ssl)

            if 'username' in session and graph_data_stats != []:
                session['error'] = "Already logged in"
            elif type(exist) == int:
                config = model.user_role_config(username)

                if config:
                    role_exist = config['user roles'][username]
                    users_data = mongo.db.users_data.find_one(
                        {'server': server})
                    resources = mongo.db.resources.find_one(
                        {'server': server})

                    session['username'] = username
                    plotting_object = graph_generator_DB.GraphGenerator(
                        username,
                        users_data['info'],
                        config['project_visible'],
                        role_exist,
                        resources)
                    graph_data_stats = plotting_object.graph_generator()
                    project_lists = plotting_object.\
                        project_list_generator()

                else:
                    session['error'] = "User role doesn't exist"

            else:
                session['error'] = exist[0]

        if 'error' in session:

            return redirect(url_for('auth.login_DB'))

        else:
            project_list = project_lists[0]
            project_list_ow_co_me = project_lists[1]
            graph_data = graph_data_stats[0]
            stats_data = graph_data_stats[1]
            return render_template('dashboards/stats_dashboards.html',
                                   graph_data=graph_data,

app/templates/dashboards/stats_dashboards.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- STOP user from back key start-->
    <script>
        window.history.forward(); 
    </script>
    <!-- STOP user from back key end-->
    <title>XNAT Dashboards</title>
    <!-- CSS import Start -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/common/images/Logo.png">
    <link href="/static/dashboards/css/custom.css" rel="stylesheet">
    <link href="/static/dashboards/css/custom_bootstrap_overite.css" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="icon" href="data:;base64,=">
    <!-- CSS import End -->
</head>
<div class="preloader">
</div>
<body class="skin-default-dark fixed-layout">
    <div id="main-wrapper" >
        <!-- Preloader Start -->
        <div class="preloader">
            <div class="loader">
                <div class="loader__figure"></div>
                <p class="loader__label">Plotting Data</p>
            </div>
        </div>
        <!-- Preloader End -->
        <!-- Top nav bar start-->
        <header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header">
                    <a class="navbar-brand" id="logo" href="#">
                        <img src="/static/common/images/Logo.png" class="logo">
                        XNAT Dashboards
                    </a>
                </div>
                <div class="navbar-collapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item hidden-sm-up"> <a class="nav-link nav-toggler waves-effect waves-light" href="javascript:void(0)"><i class="fa fa-bars"></i></a></li>
                    </ul>
                    <ul class="navbar-nav my-lg-0">
                        <li>
                            <i class="fa fa-user username" aria-hidden="true"></i>
                        </li>
                        <li>
                            &nbsp&nbsp&nbsp
                        </li>
                        <li class="nav-item dropdown username">
                            {{username}}   
                        </li>
                        <li>
                            &nbsp&nbsp&nbsp
                        </li>
                        <li>
                            <i class="fa fa-sign-out logout" aria-hidden="true"></i>
                        </li>
                        <li>
                            &nbsp&nbsp
                        </li>
                        <li class="nav-item dropdown">
                            <a href="{{url_for('dashboards.logout')}}" class="logout" > Logout</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Top nav bar end-->
        <!-- Left sidebar start-->
        <aside class="left-sidebar">
            <div class="d-flex no-block nav-text-box align-items-center left_pane">
                Dashboards
                <a class="waves-effect waves-dark ml-auto hidden-sm-down" href="javascript:void(0)"><i class="fa fa-bars"></i></a>
                <a class="nav-toggler waves-effect waves-dark ml-auto hidden-sm-up" href="javascript:void(0)"><i class="fa fa-bars"></i></a>
            </div>
            <div class="scroll-sidebar">
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li id="overview"> <a class="waves-effect waves-dark" href="#" aria-expanded="false"><i class="fa fa-eye"></i><span class="hide-menu">Overview</span></a></li>
                        <li id="projects"> <a class="waves-effect waves-dark" href="#" aria-expanded="false"><i class="fa fa-list"></i><span class="hide-menu">Projects</span></a></li>     
                        <li id="projects_ow_co_me"> <a class="waves-effect waves-dark" href="#" aria-expanded="false"><i class="fa fa-list"></i><span class="hide-menu">Projects Owned, Collaborated or Member </span></a></li>                   
                        <div class="text-center m-t-30">
                            <a href="{{url_for('dashboards.logout')}}" class="waves-effect waves-light btn btn-outline-danger"> Logout </a>
                        </div>
                    </ul>
                </nav>
            </div>
        </aside>
        <!-- Left sidebar end-->
        <!-- Plotly graphs container start -->
        <div class="page-wrapper ">
            <div class="container-fluid ">
                <div class="row page-titles">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor overview_part">Overview Dashboard</h4>
                        <h4 class="text-themecolor project_part">All Visible Projects Dashboard</h4>
                        <h4 class="text-themecolor project_part_ow_co_me">Projects Owned, Collaborated or Member Dashboard</h4>
                    </div>
                    <div class="col-md-7 align-self-center text-right">
                        <div class="d-flex justify-content-end align-items-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0)">Connected</a></li>
                                <li class="breadcrumb-item active">{{server}}</li>
                            </ol>
                            {% if db is sameas true%}
                            <button type="button" class="btn btn-outline-info d-lg-block m-l-15"> Database </button>
                            {% endif %}
                            {% if db is sameas false %}
                            <button type="button" class="btn btn-outline-info d-lg-block m-l-15"> API </button>
                            {% endif %}
                            
                        </div>
                    </div>
                </div>
                <div class = "overview_part">
                    <!-- Counter Start -->
                    <div class = "card">
                        <div class="card-body">
                                <div class="row">
                                    {% for key in stats_data %}
                                    <div class="col">
                                        <div class="counter">
                                            <h2 class="timer count-title count-number" data-to="{{stats_data[key]}}" data-speed="1000"></h2>
                                            <p class="count-text ">{{key}}</p>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                        </div>
                    </div>
                    <!-- Counter End -->
                    <!-- Graph plotting Start -->
                    {% for i in graph_data %}
                    <div class="row">
                        {% for j in i %}
                        {% for key in j %}
                            <div class="col-lg-6" id="myBig{{j['id']}}">
                                <div class="card">
                                    <div class="card-body" id="graph_id{{j[key]['id']}}">
                                        <i id="info_id{{j[key]['id']}}" class="fa fa-info wrapper_tooltip" aria-hidden="true" >
                                                <div id="info_text_id{{j[key]['id']}}" class="tooltip"></div>
                                        </i>
                                        <div id="graph_body{{j[key]['id']}}"><!-- Plotly chart will be drawn inside this DIV --></div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        {% endfor %}
                    </div>
                    {% endfor %}
                    <!-- Graph plotting End -->
                <!-- Modal start for drill down data-->
                    <div class="modal fade" id="drillDown" tabindex="-1" role="dialog" aria-labelledby="drillDownTile" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="drillDownTitle"></h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        </button>
                                </div>
                                <div class="modal-body" id="modalBodyDrillDown">
                    
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- Modal end for drill down data -->
                </div>
            </div>
            <!-- Project List Start -->
            <!-- Project list for all visible projects Start -->
            <div class="project_part">
                {% for i in project_list%}
                <div class="row">
                    {% for j in i%}
                        <div class="col-lg-3">
                            {% if db is sameas true%}
                            <a href="/dashboards/db/project/{{j}}" target="_blank"> 
                            {% endif %}
                            {% if db is sameas false%}
                            <a href="/dashboards/project/{{j}}" target="_blank"> 
                            {% endif %}
                                <div class="card project">
                                    <div class="card-body" >
                                        {{j}}
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
            <!-- Project list for all visible projects End -->
            <!-- Project list for owned, collab or member projects Start -->
            <div class="project_part_ow_co_me">
                {% for i in project_list_ow_co_me%}
                <div class="row">
                    {% for j in i%}
                        <div class="col-lg-3">
                            {% if db is sameas true%}
                            <a href="/dashboards/db/project/{{j}}" target="_blank"> 
                            {% endif %}
                            {% if db is sameas false%}
                            <a href="/dashboards/project/{{j}}" target="_blank"> 
                            {% endif %}
                                <div class="card project">
                                    <div class="card-body" >
                                        {{j}}
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
            <!-- Project list for owned, collab or member projects End -->
            <!-- Project List End -->
        </div>
        <!-- Plotly graphs container end-->
        <!-- Footer start-->
        <footer class="footer">
            © 2020 XNAT Dashboards
        </footer>
        <!-- Footer end-->
    </div>    
    <!-- Js include Start -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="/static/dashboards/js/custom.js"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    {% if db is sameas true%}
    <script src="/static/dashboards/js/plotly_chart_generator.js"></script>
    {% endif %}
    {% if db is sameas false%}
    <script src="/static/dashboards/js/plotly_chart_generator_r.js"></script>
    {% endif %}
    <script src="/static/dashboards/js/graph_descriptor.js"></script>
    {% for i in graph_data%}
        {% for j in i%}
            <script>         
                chart_generator({{ j | tojson}});
            </script>
        {%endfor%}
    {%endfor%}
    <script src="/static/dashboards/js/per_project.js"></script>
    <!-- Js include End -->
</body>

</html>